#!/usr/bin/env python
# coding: utf8
"""
Conversion from c file generated by image2LCD to Python file usable with microcontroler
"""

#####################################################
#Define filename filename
#Change image name !!!

name = 'TESTU'

#####################################################
filename = name+'.c'

c_file = open(filename, 'r')
python_file = open(name+ '.py', "w")

try:
    """
    Reading header file to collect date and create adapted header for the converted file to keep it readable (except reverse color)
    """
    image_car = ''
    nblines = len(open(filename, 'r').readlines())
    #Remove first line
    c_file.readline()
    for aline in range(1,nblines):
        c_data = c_file.readline().rstrip()
        c_data = c_data.replace('};','')
        c_data = c_data.replace('0X', '\\x')
        if aline == nblines - 1:
            image_car = (image_car + c_data)[:-1]
        else:
            image_car = image_car + c_data
    
    python_file.write('image=b\''+image_car+'\'')

finally:
    c_file.close()
    python_file.close()
